# Use an official Golang runtime as a parent image
FROM golang:latest

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app3
COPY . .
COPY . /app
COPY go.mod .
COPY go.sum .
COPY .env /app          

# Download and install any dependencies specified in your go.mod and go.sum 
RUN go mod download
RUN go get github.com/go-playground/validator/v10
RUN go get github.com/go-kit/log
RUN go get github.com/go-kit/log/level
RUN go get github.com/google/uuid
RUN go get github.com/joho/godotenv
RUN go get gorm.io/gorm

# Build the Go app
RUN go build -o main .

# Expose port 9000 to the outside world
EXPOSE 9000

# Command to run the executable
CMD ["./main",".env"]
ENTRYPOINT ["./main",".env"]




